config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  get 'about' => 'welcome#about', as: :about

  namespace :admin do
    resources :posts do
      resources :comments, only: [:destroy]
    end
  end

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :manage, Comment, user_id: user.id
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/downloader.rb
class Downloader < ActiveRecord::Base
  
  has_many :pictures
  
  def download_images(params)
    params["downloader"]["image"].each do |img|
      self.pictures.create!(image: img, downloader_id: self.id)
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :post

  mount_uploader :photo, PhotoUploader
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :downloader
  mount_uploader :image, ImageUploader 
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_many :photos
  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments

  def admin?
    role == 'admin'
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to admin_post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :find_post_photos, only: [:edit, :show]

  def index
    @posts = Post.page(params[:page]).per(3)
  end

  def show
    @comments = @post.comments.page(params[:comments_page]).per(6)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(:admin, @post)
  end

  def update
    @post.update(post_params)
    respond_with(:admin, @post)
  end

  def destroy
    @post.destroy
    respond_with(:admin, @post)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def find_post_photos
    @post_photos = @post.photos
  end

  def post_params
    attributes = [
      :title, :body,
      photos_attributes: [:post_id, :photo, :_destroy, :id]
    ]
    params.require(:post).permit(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'application_responder'

  self.responder = ApplicationResponder
  respond_to :html, :js

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private

    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/downloaders_controller.rb
class DownloadersController < ApplicationController
  
  def new
    @downloader = Downloader.new  
  end

  def create
    @downloader = Downloader.new(downloader_params)
    if @downloader.save
      @downloader.download_images(params)
      redirect_to new_downloader_path
    end
  end

  private

  def downloader_params
    params.require(:downloader).permit(:title, :image)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.page(params[:page]).per(3)
    respond_with(@posts)
  end

  def show
    @comments = @post.comments.page(params[:comments_page]).per(6)
    @post_photos = @post.photos
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/downloaders_helper.rb
module DownloadersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/admin/posts/_form.html.haml
= form_for([:admin, @post], html: { class: 'form-horizontal' }) do |f|
  = f.fields_for :photos, Photo.new do |p|
    = render 'post_photos' if @post_photos # Выводим фотографии в action #edit
    %br
    = p.file_field :photo, multiple: true, name: 'post[photos_attributes][][photo]'

  %br
  = f.text_field :title, class: 'form-control', placeholder: 'Заголовок'
  %br
  = f.text_area :body, rows: 12, class: 'form-control', placeholder: 'Сообщение'
  %br
  = f.submit 'Отправить', class: 'btn btn-success'

app/views/admin/posts/_post_photos.html.haml
- @post_photos.each_slice(3) do |photo_post|
  .row
    - photo_post.each do |photo|
      .col-sm-6.col-md-4
        .thumbnail
          = image_tag photo.photo_url(:thumb)
          .caption
            = link_to 'Удалить изображение', admin_post_path(@post.id,
              post: { photos_attributes: { id: photo.id, _destroy: true } }),
              method: :put,
              class: 'btn btn-xs btn-danger'

app/views/admin/posts/edit.html.haml
%h2 Редактировать

= render 'form'

app/views/admin/posts/index.html.haml
%h1 Админ панель
= link_to 'Создать новую запись', new_admin_post_path, class: 'btn btn-xs btn-primary'

- @posts.each do |post|
  %h2= link_to "#{post.title}", admin_post_path(post)
  %p= "Описание: #{post.body}"
  - post.photos.each_slice(3) do |photos|
    .row
      - photos.each do |photo|
        .col-sm-6.col-md-4
          .thumbnail
            = image_tag photo.photo_url(:thumb)

  = link_to 'Редактировать', edit_admin_post_path(post), class: 'btn btn-xs btn-primary'
  = link_to 'Удалить', [:admin, post], method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-xs btn-danger'
%br
= paginate @posts, theme: 'twitter-bootstrap-3'

app/views/admin/posts/new.html.haml
%h2 Добавить

= render 'form'

app/views/admin/posts/show.html.haml
%h2= @post.title
%p= "Text: #{@post.body}"
- if @post_photos
  - @post_photos.each_slice(3) do |photos|
    .row
      - photos.each do |photo|
        .col-sm-6.col-md-4
          .thumbnail
            = image_tag photo.photo_url(:thumb)

.post-button
  = link_to 'Редактировать', edit_admin_post_path(@post), class: 'btn btn-xs btn-primary'
  = link_to 'Удалить', [:admin, @post], method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-xs btn-danger'

%h3 Комментарии
- @comments.each do |comment|
  %p= "Автор: #{comment.name}"
  %p= "Текст: #{comment.body}"
  = link_to "Удалить комментарий", [:admin, comment.post, comment], method: :delete, class: 'btn btn-xs btn-danger'
  %hr
= paginate @comments, theme: 'twitter-bootstrap-3', param_name: :comments_page

app/views/downloaders/new.html.haml
= form_for @downloader, multiple: true do |f|
  = f.text_field :title
  = f.file_field :image, multiple: true, name: "downloader[image][]"
  = f.submit

app/views/layouts/_header.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{data: { target: '#navbar-collapse', toggle: 'collapse'}, type: 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        .fa.fa-yelp>
        Timonin
    #navbar-collapse.navbar-collapse.collapse
      %p.navbar-text.pull-right
        - if user_signed_in?
          = current_user.email
          = link_to 'Выйти', destroy_user_session_path, method: :delete
        - else
          = link_to 'Войти', new_user_session_path
          = link_to 'Регистрация', new_user_registration_path

      %ul.nav.navbar-nav
        %li
          =link_to 'О проекте', about_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Timonin
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
%body
  = render 'layouts/header'
  .container
    %div
      - if flash[:notice]
        .alert.alert-success= flash[:notice]
      - if flash[:alert]
        .alert.alert-danger= flash[:alert]
      = yield

app/views/posts/_modal.html.haml
#modal_post.modal.fade
  .modal-dialog
    .modal-content
      .modal-body

app/views/posts/index.html.haml
%h1 Галлерея
- @posts.each do |post|
  %h2= link_to(post.title, post)
  %p= "Описание: #{post.body}"
  - post.photos.each_slice(3) do |photos|
    .row
      - photos.each do |photo|
        .col-sm-6.col-md-4
          .thumbnail
            = image_tag photo.photo_url(:thumb)
%br
= paginate @posts, theme: 'twitter-bootstrap-3'

app/views/posts/show.html.haml
%h2= @post.title
%p= "Text: #{@post.body}"
- if @post_photos
  - @post_photos.each_slice(3) do |photos|
    .row
      - photos.each do |photo|
        .col-sm-6.col-md-4
          .thumbnail
            = link_to image_tag(photo.photo_url(:thumb).to_s), post_path(photo_id: photo.id), id: 'post_image', remote: true

%h3 Комментарии
- @comments.each do |comment|
  %p= "Автор: #{comment.name}"
  %p= "Текст: #{comment.body}"
  %hr
= paginate @comments, theme: 'twitter-bootstrap-3', param_name: :comments_page

%h3 Оставить комментарий
= form_for([@post, @post.comments.build], html: { class: 'form-horizontal' }) do |f|
  = f.text_field :name, class: 'form-control', placeholder: 'Ваше имя'
  %br
  = f.text_area :body, class: 'form-control', placeholder: 'Комментарий'
  %br
  = f.submit 'Отправить', class: 'btn btn-success'

= render 'modal'

app/views/posts/show.js.erb
<% photo = @post.photos.find(params[:photo_id]) %>
$("<%= escape_javascript(image_tag(photo.photo_url.to_s, class: 'modal-image')) %>").appendTo('.modal-body');
$('#modal_post').modal('show');

$('body').on('hidden.bs.modal', '.modal', function () {
  $('.modal-image').remove();
});

app/views/welcome/about.html.haml
.content
  .page-header
    %h1
      Timonin
    %s1 О проэкте. блаблабла... и так далее
     

app/views/welcome/admin_page.html.haml
.content
  .page-header
  %h1 Админская страница
  = link_to "posts", admin_posts_path
  = link_to "images", images_path